#!/bin/bash

FILENAME="my_records"
today=$(date +'%a %d %m %Y')
if [ ! -d "$HOME/.local/share/health" ]
then
	mkdir "$HOME/.local/share/health"
fi

if [ ! -d "$HOME/.local/share/health/weight" ]
then
	mkdir "$HOME/.local/share/health/weight"
fi

DATA_PATH="$HOME/.local/share/health/weight" 
weight=""
chest=""
hip=""
thigh=""
waist=""
while getopts "c:ht:w:W:H:" option;do
	case $option in
		c)
				chest=$OPTARG
			;;
		H)
			hip=$OPTARG
			;;
		t)
			thigh=$OPTARG
			;;
		w)
			weight=$OPTARG
			;;
		W)
			waist=$OPTARG
			;;
		h)
			echo "Syntax: scriptTemplate [-c|h|t|w|W|H]"
			echo "options:"
			echo "c     Record chest circumference measurement in cm."
			echo "h     Record hip circumference measurement in cm."
			echo "w     Record weight circumference measurement in kg."
			echo "W     Record Waist circumference measurement in cm"
			echo "h     Help."
			exit 0
			;;
		\?)
			echo "$OPTARG : option invalide"
			exit 1
			;;
	esac
done
PATH="$DATA_PATH/$FILENAME"
if [ ! -f $PATH ]
then
	echo "DATE				WEIGHT		WAIST		HIP		CHEST" > $PATH
	echo "-----------------------------------------------------------------------------------------" >> $PATH
	
fi
echo "$today			$weight		$waist		$hip	$chest" >> $PATH
exit 0